apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
spec:
  template:
    spec:
      containers:
        - image: quay.io/metral/helloworld-go
          env:
            - name: TARGET
              value: "Go Sample v1"
